### ISSUE TITLE
Remove EoS warning in the "About Thorium" page

### ISSUE THREAD

**Issue by Daniel7689** [Alex313031/thorium-win7#1]
I think "To get future Thorium updates, you'll need Windows 10 or later. This computer is using [Insert Windows Version]." warning in the "About Thorium" page should be removed, it is false and ruins the about page aesthetically.

**Comment by Alex313031** [comment]
@Daniel7689 I will remove this.

**Comment by Alex313031** [comment]
@Daniel7689 There you go > https://github.com/Alex313031/thorium-win7/commit/d8c060e96113fdc9227f00e57a86e0b6838ed0b1

I will be making new builds based on 109.0.5414.141, with more backported patches from thorium M111

**Comment by Alex313031** [comment]
@Daniel7689 Hi, just also wanted to make a note that I just now made a patch to (on top of not showing the annoying EOS stuff), make thorium think it is still "servicable" on win7/8. This will be useful because I eventually would like to make an update server for Windows, that way thorium will auto update (on linux it already has auto update), and this will let me also extend that capability to the win7 builds.
