### ISSUE TITLE
32bit sse3

### ISSUE THREAD

**Issue by fenopa** [Alex313031/thorium-win7#10]
I didn't like the return to sse2 for 32bits. Can you also add sse3 builds for 32bits?

**Comment by Alex313031** [comment]
@fenopa I can make a 32 bit SSE3 build for you. However, if your CPU supports SSE3, it is most likely 64 bit, unless it is the last revision of pentium 4 "https://en.wikipedia.org/wiki/Pentium_4#Prescott" prescott.

If it a 64 bit CPU, it is almost always better to run a 64 bit edition of win7/8/8.1.

Most people who are running 32 bit Win7 are on old processors, where an SSE2 build makes sense, especially since Chrome and Chromium are normally compiled with SSE3

**Comment by Alex313031** [comment]
@fenopa For the last M109 build, I made seperate SSE2 and SSE3 32 bit releases. https://github.com/Alex313031/thorium-win7/releases/tag/M109.0.5414.172
