### ISSUE TITLE
i dont understand wtch version is good for me

### ISSUE THREAD

**Issue by Soheil777** [Alex313031/thorium-win7#27]
**Add all the stuffz here**
hi bro
My PC came from Stone Age AMD 5200 with 2 cores before the thread existed
I use Windows 7 64-bit
can you tell me which version is best for me, the most complete, fast, and secure
thank you so much and god bless

**Comment by hetszunyukapanyanyimonyok** [comment]
Based on your processor and the guidelines.
"
AVX builds require a CPU with support for AVX instructions (generally newer than 2012)
AVX2 builds require a CPU with support for AVX2 instructions (generally newer than 2015)
SSE3 builds requires a CPU with support for SSE3 instructions (the default for Chromium, almost all CPUs support this)
"
SSE3 build what you need. (Because of the 2007 processor).

**Comment by Alex313031** [comment]
@Soheil777 @hetszunyukapanyanyimonyok Im actually making a nice little explainer since I get issues alot relating to which version to download and what is AVX, etc.

The explainer will be on the website, in the github wiki, and in the docs dir as an .md file.

**Comment by hetszunyukapanyanyimonyok** [comment]
@Alex313031 thanks! That's a good idea! Any news about newer version?

**Comment by Alex313031** [comment]
@hetszunyukapanyanyimonyok Just released yet another 109 version, the last one, today.

Heres the doc im talking about that I just made > https://github.com/Alex313031/thorium-win7/blob/main/docs/ABOUT_RELEASES.md

New builds based on Chromium/Supermium M119 will be coming out in early january.
