### ISSUE TITLE
Readd the "UI Layout" option removed in chromium 71

### ISSUE THREAD

**Issue by Masaru2** [Alex313031/thorium-win7#8]
Is there any interest to restore the flag to restore the old chrome UI?

Apparently the flag is still present in chromium, althrough desactivated according to this:
https://github.com/chromium/chromium/commit/d7742835a968dae51c23493654e971c6eb361c9a

**Comment by gz83** [comment]
Thank you for your suggestions, we will evaluate them, but please note that don't expect every suggestion to be implemented

@Masaru2

**Comment by Alex313031** [comment]
@gz83 @Masaru2 I ALSO love the UI of Chromium from then. This is why I made builds of Chromium M69, with some patches applied > https://github.com/Alex313031/CR-69-72

That said, the amount of work this would take would not be worth it for me, assuming I could even get it right. They have moved alot of stuff to WebUI, and conglomerated alot of file in the //ui/ and //chrome/ui/ directories. It would not be as simple as making a revert patch since M71 is 5 years old.

**Comment by Masaru2** [comment]
There's no windows builds

**Comment by Alex313031** [comment]
@Masaru2 You can find builds of Chromium 69? Are you saying you want me to make a compiler optimized Windows one?

**Comment by Alex313031** [comment]
@Masaru2 Just made some Windows builds of both M69, and M87 (last to support ftp:// URLs and flash player, it includes a flash installer!)

> https://github.com/Alex313031/CR-69-72/releases/tag/M69.0.3497.128
> https://github.com/Alex313031/CR-87/releases/tag/M87.0.4280.168
